version: '3.8'
services:
  java-maven-app:
    image: danbutuc/demo-app:1.0  # Add "image" key
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-pwd
